[package]
name = "kogeki"
version = "0.1.0"
authors = ["Kei Sugano <kei.sugano@h-t.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
curl = "0.4.30"
